server:
  port: 9002

spring:
  datasource:
    url:      "jdbc:mysql://localhost:3306/spring-demo_login"
    username: "spring-demo"
    password: "spring-demo"
    
    hikari:
      data-source-properties:
        useSSL:         false
        serverTimezone: "JST"

  jpa:
    properties:
      hibernate.dialect:                "org.hibernate.dialect.MySQL5Dialect"
      hibernate.dialect.storage_engine: "innodb"
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true

  mail:
    protocol: "smtp"
    host:     "smtp.gmail.com"
    port:     587
    username: "[env]"
    password: "[env]"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    default-encoding: "UTF-8"

logging:
  level:
    com.example: DEBUG

app:
  mail:
    from: "[env]"
    template:
      template-mode:      HTML
      prefix:             "templates/mail/"
      suffix:             ".html"
      character-encoding: UTF-8
      cacheable:          true
