
spring:
  flyway:    enabled: true
    encoding: UTF-8
    validate-on-migrate: true
    clean-on-validation-error: true
    url: "jdbc:mysql://localhost:3306/spring"
    user: "root"
    password: "spring" 

  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    
  messages:
    basename: "i18n/messages"
    cache-duration: -1
    encoding: UTF-8
    
  datasource:    url: "jdbc:mysql://localhost:3306/spring"
    username: "spring"
    password: "spring" 
    hikari:
      data-source-properties:
        useSSL:         false
        serverTimezone: "JST"
        allowPublicKeyRetrieval: true

  jpa:    hibernate:      ddl-auto: validate
    show-sql: true

  jackson:    date-format: "yyyy-MM-dd'T'HH:mm:ss"
    property-naming-strategy: "com.fasterxml.jackson.databind.PropertyNamingStrategy.SnakeCaseStrategy"
    default-property-inclusion: non-empty
      
#   serialization:#   deserialization:    
logging:  level:
    root: OFF    com.example: DEBUG
    org.springframework: INFO