CREATE TABLE IF NOT EXISTS user_emails (

 email VARCHAR(255) NOT NULL,
 
 UNIQUE KEY UIDX_USER_EMAILS_01 (email)
 
) ENGINE=InnoDB;

DROP   TRIGGER IF EXISTS TRG_BI_USERS_BY_EMAIL;
DROP   TRIGGER IF EXISTS TRG_BU_USERS_BY_EMAIL;

DELIMITER //

CREATE  TRIGGER TRG_BI_USERS_BY_EMAIL
    BEFORE INSERT ON users FOR EACH ROW

BEGIN
    INSERT INTO user_emails (email) VALUES (new.email);
END
//
CREATE TRIGGER TRG_BU_USERS_BY_EMAIL
    BEFORE UPDATE ON users FOR EACH ROW

BEGIN
	DELETE FROM user_emails WHERE email = old.email;
    INSERT INTO user_emails (email) VALUES ( new.email );
END
//

